// ✅ Utility function to show error for leading spaces in text input fields (allows space entry)
function preventLeadingSpaceOnInput(inputElement, errorElement) {
    if (!inputElement || !errorElement) return;
    
    inputElement.addEventListener('input', function() {
        if (this.value.length > 0 && this.value[0] === ' ') {
            errorElement.textContent = 'Spaces are not allowed at the beginning.';
            inputElement.classList.add('input-error');
            inputElement.classList.remove('input-success');
        } else {
            // Clear error when space is removed
            if (errorElement.textContent === 'Spaces are not allowed at the beginning.') {
                errorElement.textContent = '';
                inputElement.classList.remove('input-error');
            }
        }
    });
}

// ✅ Email validation - delegates to check_user.js for real-time validation
function validateEmail() {
    if (typeof window.validateAndCheckEmail === 'function') {
        window.validateAndCheckEmail();
    }
}

function calculateAge() {
    var birthdate = document.getElementById("birthday").value;
    var ageInput = document.getElementById("Age");
    
    if (birthdate) {
        var today = new Date();
        var bday = new Date(birthdate);
        
        // Check if the year is beyond 2025 or if the date is in the future
        const birthYear = bday.getFullYear();
        if (birthYear > 2025 || bday > today) {
            // Show error in birthday field
            const birthdayInput = document.getElementById("birthday");
            const birthdayError = ensureErrorElement('birthdayError', birthdayInput);
            if (birthdayError) {
                birthdayError.textContent = "Age Must not be in a future";
                birthdayInput.classList.add("input-error");
                birthdayInput.classList.remove("input-success");
            }
            // Clear age field
            ageInput.value = "";
            return;
        }

        var age = today.getFullYear() - bday.getFullYear();
        var monthDiff = today.getMonth() - bday.getMonth();

        if (monthDiff < 0 || (monthDiff === 0 && today.getDate() < bday.getDate())) {
            age--;
        }

        ageInput.value = age;
        
        // ✅ Validate age after calculation
        validateAge();
    }
}

// Add restrictions to Age and ID Number fields when DOM is loaded
document.addEventListener('DOMContentLoaded', function() {
    const ageInput = document.getElementById("Age");
    const idInput = document.getElementById("idNumber");
    
    // Age field restrictions
    if (ageInput) {
        // Make age field visually appear as read-only
        ageInput.style.backgroundColor = '#f8f9fa';
        ageInput.style.cursor = 'not-allowed';
        
        // Add tooltip to explain why it's read-only
        ageInput.setAttribute('title', 'Age is automatically calculated from your birthday');
        
        // Prevent any attempts to manually edit the age field
        ageInput.addEventListener('keydown', function(e) {
            e.preventDefault();
            return false;
        });
        
        ageInput.addEventListener('paste', function(e) {
            e.preventDefault();
            return false;
        });
        
        ageInput.addEventListener('input', function(e) {
            // If somehow the value was changed, recalculate from birthday
            calculateAge();
        });
        
        // Prevent mouse wheel from changing the number input
        ageInput.addEventListener('wheel', function(e) {
            e.preventDefault();
            return false;
        });
    }
    
    // ID Number field restrictions
    if (idInput) {
        // Make ID field visually appear as read-only
        idInput.style.backgroundColor = '#f8f9fa';
        idInput.style.cursor = 'not-allowed';
        
        // Add tooltip to explain why it's read-only
        idInput.setAttribute('title', 'ID Number is automatically generated by the system');
        
        // Prevent any attempts to manually edit the ID field
        idInput.addEventListener('keydown', function(e) {
            e.preventDefault();
            return false;
        });
        
        idInput.addEventListener('paste', function(e) {
            e.preventDefault();
            return false;
        });
        
        idInput.addEventListener('input', function(e) {
            // If somehow the value was changed, prevent it by keeping the original value
            // The ID should only be set by the generate_id.js script
            e.preventDefault();
        });
        
        // Prevent mouse wheel from changing the input if it's a number type
        idInput.addEventListener('wheel', function(e) {
            e.preventDefault();
            return false;
        });
    }
});

// ✅ Age validation function
function validateAge() {
    const input = document.getElementById("Age");
    const error = document.getElementById("ageError");
    const value = parseInt(input.value);
    
    if (isNaN(value) || value === "") {
        error.textContent = "Age is required.";
        input.classList.add("input-error");
        input.classList.remove("input-success");
    } else if (value < 18) {
        error.textContent = "Must be 18 years old or above to register.";
        input.classList.add("input-error");
        input.classList.remove("input-success");
    } else if (value > 120) {
        error.textContent = "Please enter a valid age.";
        input.classList.add("input-error");
        input.classList.remove("input-success");
    } else {
        error.textContent = "";
        input.classList.remove("input-error");
        input.classList.add("input-success");
    }
}

// ✅ Enhanced form validation - checks all errors before submission
function validateForm(){
    // Kick all per-field validators to populate inline messages
    if (typeof validateFname === 'function') validateFname();
    if (typeof validateMiddleName === 'function') validateMiddleName();
    if (typeof validateLastName === 'function') validateLastName();
    if (typeof calculateAge === 'function') calculateAge(); // will call validateAge
    if (typeof validateAge === 'function') validateAge();
    if (typeof window.validateAndCheckEmail === 'function') window.validateAndCheckEmail();
    if (typeof validateBirthday === 'function') validateBirthday();
    if (typeof validateZipCode === 'function') validateZipCode();
    if (typeof validatePassword === 'function') validatePassword();
    if (typeof validateConfirmPassword === 'function') validateConfirmPassword();
    if (typeof validateStreet === 'function') validateStreet();
    if (typeof validateBarangay === 'function') validateBarangay();
    if (typeof validateCity === 'function') validateCity();
    if (typeof validateProvince === 'function') validateProvince();
    if (typeof validateCountry === 'function') validateCountry();

    // Minimal required checks for fields without dedicated validators
    const requiredMap = {
        Firstname: 'fnameError',
        LastName: 'lastNameError',
        birthday: 'birthdayError',
        Age: 'ageError',
        email: 'emailError',
        Password: 'passwordError',
        RePassword: 'confirmPasswordError',
        Street: 'streetError',
        Barangay: 'barangayError',
        City: 'cityError',
        Province: 'provinceError',
        Country: 'countryError',
        ZipCode: 'zipCodeError'
    };

    Object.keys(requiredMap).forEach(function(fieldId){
        const el = document.getElementById(fieldId);
        const err = document.getElementById(requiredMap[fieldId]);
        if (el && err && el.value.trim() === ''){
            err.textContent = `${err.getAttribute('data-name') || el.getAttribute('data-name') || el.getAttribute('placeholder') || el.name || fieldId} is required.`;
            el.classList.add('input-error');
            el.classList.remove('input-success');
        }
    });

    // If any field still has input-error, block submit without alert
    const hasErrors = document.querySelectorAll('.input-error').length > 0;
    return !hasErrors;
}

    // ✅ Helper function to find the first error in input (left to right)
function findFirstError(raw, value, max, allowHyphens = false) {
    const errors = [];
    
    // Check for leading space (position 0)
    if (raw.length > 0 && raw[0] === ' ') {
        errors.push({ position: 0, message: "Spaces are not allowed at the beginning." });
    }
    
    // Check for hyphen (find first position) - only if not allowed
    if (!allowHyphens) {
        const hyphenIndex = raw.indexOf('-');
        if (hyphenIndex !== -1) {
            errors.push({ position: hyphenIndex, message: "Hyphens are not allowed in this field." });
        }
    }
    
    // Check for multiple spaces (find first position)
    const multipleSpacesMatch = raw.match(/\s{2,}/);
    if (multipleSpacesMatch) {
        errors.push({ position: raw.indexOf(multipleSpacesMatch[0]), message: "Double spaces are not allowed." });
    }
    
    // Check for digits (find first position) - check in raw to get correct position
    for (let i = 0; i < raw.length; i++) {
        if (/\d/.test(raw[i])) {
            errors.push({ position: i, message: "Numbers are not allowed." });
            break;
        }
    }
    
    // Check for special characters (find first position) - only true special chars, not digits
    // This should come after digit check so digits are caught first
    for (let i = 0; i < raw.length; i++) {
        if (/[^a-zA-Z0-9\s]/.test(raw[i])) {
            errors.push({ position: i, message: "Special characters are not allowed." });
            break;
        }
    }

    // Check for trailing space (last position) - but only if no other errors found earlier
    if (raw.endsWith(' ') && raw.trim().length > 0) {
        errors.push({ position: raw.length - 1, message: "Cannot end with a space." });
    }
    
    // Check for consecutive letters (find first position)
    const consecutiveMatch = value.match(/(.)\1{2,}/i);
    if (consecutiveMatch) {
        const matchPos = value.indexOf(consecutiveMatch[0]);
        errors.push({ position: matchPos, message: "Three (3) consecutive letters are not allowed." });
    }

    // Check for all caps (affects whole string, but check after other errors)
    if (value === value.toUpperCase() && value.length >= 2) {
        errors.push({ position: 0, message: "All capital letters are not allowed." });
    }
    
    // Check for consecutive capitals (find first position)
    const consecutiveCapMatch = value.match(/([A-Z][A-Z])/);
    if (consecutiveCapMatch) {
        errors.push({ position: value.indexOf(consecutiveCapMatch[0]), message: "Consecutive capital letters are not allowed." });
    }
    
    // Check for max length (affects end, but check after other errors)
    if (value.length >= max) {
        errors.push({ position: max, message: `Maximum ${max} characters reached.` });
    }
    
    // Check capitalization errors (find first position)
    if (value.length > 0) {
        if (value[0] !== value[0].toUpperCase()) {
            errors.push({ position: 0, message: "Must start with a capital letter." });
        } else {
            const parts = value.split(/\s+/).filter(Boolean);
            if (parts.length >= 2 && parts[1] && parts[1].charAt(0) !== parts[1].charAt(0).toUpperCase()) {
                const secondWordStart = value.indexOf(parts[1]);
                errors.push({ position: secondWordStart, message: "The second word must start with a capital letter." });
            } else {
                // Check for other capitalization issues
                for (let i = 0; i < value.length; i++) {
                    const char = value[i];
                    if (i === 0 || value[i-1] === ' ') {
                        // Should be uppercase
                        if (/[a-z]/.test(char)) {
                            errors.push({ position: i, message: `'${char}' should be uppercase` });
                            break;
                        }
                    } else if (/[a-zA-Z]/.test(value[i-1]) && /[A-Z]/.test(char) && !/[A-Z]/.test(value[i-1])) {
                        // Middle of word should be lowercase
                        errors.push({ position: i, message: `'${char}' should be lowercase` });
                        break;
                    }
                }
            }
        }
    }
    
    // Return the error with the smallest position (leftmost error)
    if (errors.length > 0) {
        errors.sort((a, b) => a.position - b.position);
        return errors[0].message;
    }
    
    return null;
}

// ✅ Real-time validation with min & max limit - Shows FIRST error from left to right
function validateFname() {
    const input = document.getElementById("fname");
    const error = document.getElementById("fnameError");
    const raw = input.value;
    const value = raw.trim();
    const min = parseInt(input.getAttribute("minlength"));
    const max = parseInt(input.getAttribute("maxlength"));
    const pattern = /^([A-Z][a-z]*)(\s[A-Z][a-z]*)*$/; // Only letters and spaces with proper title case
    
    // ✅ Check if empty first
    if (value === "") {
        error.textContent = "First Name is required.";
        input.classList.add("input-error");
        input.classList.remove("input-success");
        return;
    }
    
    // ✅ Find the first error from left to right
    const firstError = findFirstError(raw, value, max);
    
    if (firstError) {
        error.textContent = firstError;
        input.classList.add("input-error");
        input.classList.remove("input-success");
    
        // Handle max length by truncating
        if (firstError.includes("Maximum")) {
        input.value = value.substring(0, max);
        }
        return;
    }
    
    // ✅ Final pattern check
    if (!pattern.test(value)) {
        const parts = value.split(/\s+/).filter(Boolean);
        if (value.length > 0 && value[0] !== value[0].toUpperCase()) {
            error.textContent = "Must start with a capital letter.";
        } else if (parts.length >= 2 && parts[1] && parts[1].charAt(0) !== parts[1].charAt(0).toUpperCase()) {
            error.textContent = "The second word must start with a capital letter.";
        } else {
            const incorrectChars = checkCapitalization(value);
            if (incorrectChars.length > 0) {
                error.textContent = incorrectChars.join(", ");
            } else {
                error.textContent = "Each word should start with a capital letter only.";
            }
        }
        input.classList.add("input-error");
        input.classList.remove("input-success");
        return;
    }
    
    // ✅ SUCCESS: No errors found
    error.textContent = "";
    input.classList.remove("input-error");
    input.classList.add("input-success");
}
// ✅ Real-time validation with min & max limit - Shows FIRST error from left to right
function validateMiddleName() {
    const input = document.getElementById("middleName");
    const error = document.getElementById("middleNameError");
    const raw = input.value;
    const value = raw.trim();
    const min = parseInt(input.getAttribute("minlength"));
    const max = parseInt(input.getAttribute("maxlength"));
    const pattern = /^([A-Z][a-z]*)(\s[A-Z][a-z]*)*$/; // Only letters and spaces with proper title case
    
    // ✅ Check if empty first (optional field)
    if (value === "") {
        input.classList.remove("input-error");
        input.classList.remove("input-success");
        error.textContent = "";
        return; // Optional field is empty - no error
    }
    
    // ✅ Find the first error from left to right
    const firstError = findFirstError(raw, value, max);
    
    if (firstError) {
        error.textContent = firstError;
        input.classList.add("input-error");
        input.classList.remove("input-success");
        
        // Handle max length by truncating
        if (firstError.includes("Maximum")) {
        input.value = value.substring(0, max);
        }
        return;
    }
    
    // ✅ Final pattern check
    if (!pattern.test(value)) {
        const parts = value.split(/\s+/).filter(Boolean);
        if (value.length > 0 && value[0] !== value[0].toUpperCase()) {
            error.textContent = "Must start with a capital letter.";
        } else if (parts.length >= 2 && parts[1] && parts[1].charAt(0) !== parts[1].charAt(0).toUpperCase()) {
            error.textContent = "The second word must start with a capital letter.";
        } else {
            const incorrectChars = checkCapitalization(value);
            if (incorrectChars.length > 0) {
                error.textContent = incorrectChars.join(", ");
            } else {
                error.textContent = "Each word should start with a capital letter only.";
            }
        }
        input.classList.add("input-error");
        input.classList.remove("input-success");
        return;
    }
    
    // ✅ SUCCESS: No errors found
    error.textContent = "";
    input.classList.remove("input-error");
    input.classList.add("input-success");
}

// ✅ Real-time validation with min & max limit - Shows FIRST error from left to right
function validateLastName() {
    const input = document.getElementById("LastName");
    const error = document.getElementById("lastNameError");
    const raw = input.value;
    const value = raw.trim();
    const min = parseInt(input.getAttribute("minlength"));
    const max = parseInt(input.getAttribute("maxlength"));
    const pattern = /^([A-Z][a-z]*)(\s[A-Z][a-z]*)*$/; // Only letters and spaces with proper title case
    
    // ✅ Check if empty first
    if (value === "") {
        error.textContent = "Last Name is required.";
        input.classList.add("input-error");
        input.classList.remove("input-success");
        return;
    }
    
    // ✅ Find the first error from left to right
    const firstError = findFirstError(raw, value, max);
    
    if (firstError) {
        error.textContent = firstError;
        input.classList.add("input-error");
        input.classList.remove("input-success");
        
        // Handle max length by truncating
        if (firstError.includes("Maximum")) {
        input.value = value.substring(0, max);
        }
        return;
    }
    
    // ✅ Final pattern check
    if (!pattern.test(value)) {
        const parts = value.split(/\s+/).filter(Boolean);
        if (value.length > 0 && value[0] !== value[0].toUpperCase()) {
            error.textContent = "Must start with a capital letter.";
        } else if (parts.length >= 2 && parts[1] && parts[1].charAt(0) !== parts[1].charAt(0).toUpperCase()) {
            error.textContent = "The second word must start with a capital letter.";
        } else {
            const incorrectChars = checkCapitalization(value);
            if (incorrectChars.length > 0) {
                error.textContent = incorrectChars.join(", ");
            } else {
                error.textContent = "Each word should start with a capital letter only.";
            }
        }
        input.classList.add("input-error");
        input.classList.remove("input-success");
        return;
    }
    
    // ✅ SUCCESS: No errors found
    error.textContent = "";
    input.classList.remove("input-error");
    input.classList.add("input-success");
}

// ✅ Helper function for Street validation - allows hyphens and numbers (but not at start)
function findFirstErrorStreet(raw, value, max) {
    const errors = [];
    
    // Check for leading space (position 0)
    if (raw.length > 0 && raw[0] === ' ') {
        errors.push({ position: 0, message: "Spaces are not allowed at the beginning." });
    }
    
    // Check for multiple spaces (find first position)
    const multipleSpacesMatch = raw.match(/\s{2,}/);
    if (multipleSpacesMatch) {
        errors.push({ position: raw.indexOf(multipleSpacesMatch[0]), message: "Double spaces are not allowed." });
    }
    
    // Check for space after hyphen (e.g., "Purok- 3")
    const spaceAfterHyphen = /-\s/.exec(value);
    if (spaceAfterHyphen) {
        errors.push({ position: value.indexOf(spaceAfterHyphen[0]), message: "Remove the space after the hyphen." });
    }
    
    // Check for special characters (find first position) - allow hyphens and numbers
    for (let i = 0; i < raw.length; i++) {
        if (/[^a-zA-Z0-9\s-]/.test(raw[i])) {
            if (/_/.test(raw[i])) {
                errors.push({ position: i, message: "Only letters, spaces, and hyphens are allowed." });
        } else {
                errors.push({ position: i, message: "Special character is not allowed." });
        }
            break;
        }
    }
    
    // Check for lowercase letters after numbers (e.g., "P-3a" should be invalid)
    for (let i = 0; i < value.length - 1; i++) {
        if (/\d/.test(value[i]) && /[a-z]/.test(value[i + 1])) {
            errors.push({ position: i + 1, message: "After a number, letters must be uppercase." });
            break;
        }
    }
    
    // Check for trailing hyphen FIRST (higher priority)
    if (value.endsWith('-')) {
        errors.push({ position: value.length - 1, message: "Street cannot end with a hyphen." });
    }
    
    // Check for trailing space
    if (raw.endsWith(' ') && raw.trim().length > 0) {
        errors.push({ position: raw.length - 1, message: "Cannot end with a space." });
    }
    
    // Check for consecutive letters
    const consecutiveMatch = value.match(/(.)\1{2,}/i);
    if (consecutiveMatch) {
        errors.push({ position: value.indexOf(consecutiveMatch[0]), message: "Three (3) consecutive letters are not allowed." });
    }
    
    // Check for all caps (only if length >= 4 and no hyphen at end) - more lenient for short inputs
    if (value === value.toUpperCase() && value.length >= 4 && /^[A-Z\s\-]+$/.test(value) && !value.endsWith('-')) {
        errors.push({ position: 0, message: "All capital letters are not allowed in Street." });
    }
    
    // Check for consecutive capitals
    const consecutiveCapMatch = value.match(/([A-Z][A-Z])/);
    if (consecutiveCapMatch) {
        errors.push({ position: value.indexOf(consecutiveCapMatch[0]), message: "Consecutive capital letters are not allowed." });
    }
    
    // Disallow ordinal numbers (e.g., 12th, 3rd) anywhere in the input
    // Also catch truncated ordinals like "12t", "3r", "2n", "1s" and any single-letter suffix (e.g., "3324r")
    const ordinalMatch = raw.match(/\b\d+(?:st|nd|rd|th|[A-Za-z])\b/i);
    if (ordinalMatch) {
        const matchText = ordinalMatch[0];
        const matchPos = raw.indexOf(matchText);
        // Allow patterns like: Word-3A (e.g., "Purok-3A") where there is a letter, a hyphen,
        // then the digits+single UPPERCASE letter — treat these as valid unit/lot identifiers.
        const beforeIdx = matchPos - 1;
        const twoBeforeIdx = matchPos - 2;
        const afterChar = raw.charAt(matchPos + matchText.length - 1);

        const isPrefixedByLetterHyphen = (
            beforeIdx >= 0 && twoBeforeIdx >= 0 &&
            raw.charAt(beforeIdx) === '-' && /[A-Za-z]/.test(raw.charAt(twoBeforeIdx))
        );

        if (!(isPrefixedByLetterHyphen && /[A-Z]/.test(afterChar))) {
            errors.push({ position: matchPos, message: "No ordinal numbers; use numbers with street name (e.g., 12 Street)." });
        }
    }

    // Check if the input is numbers only (allow spaces and hyphens between numbers)
    const strippedForDigits = raw.replace(/[\s-]/g, '');
    if (strippedForDigits.length > 0 && /^\d+$/.test(strippedForDigits)) {
        errors.push({ position: 0, message: "Street/Purok must include words after the number." });
    }
    
    // Check for max length
    if (value.length >= max) {
        errors.push({ position: max, message: `Maximum ${max} characters reached.` });
    }
    
    // Check capitalization errors: only require first letter capitalized if the field starts with a letter
    if (value.length > 0) {
        if (/^[A-Za-z]/.test(value) && !/^[A-Z]/.test(value)) {
            errors.push({ position: 0, message: "Street must start with a capital letter." });
        } else {
            const parts = value.split(/\s+/).filter(Boolean);
            if (parts.length >= 2 && /^[A-Za-z]/.test(parts[1]) && /^[a-z]/.test(parts[1])) {
                const secondWordStart = value.indexOf(parts[1]);
                errors.push({ position: secondWordStart, message: "The second word must start with a capital letter." });
            }
        }
    }
    
    if (errors.length > 0) {
        errors.sort((a, b) => a.position - b.position);
        return errors[0].message;
    }
    
    return null;
}

// ✅ Helper function for Barangay validation - allows hyphens, no numbers
function findFirstErrorBarangay(raw, value, max) {
    const errors = [];
    
    // Check for leading space (position 0)
    if (raw.length > 0 && raw[0] === ' ') {
        errors.push({ position: 0, message: "Spaces are not allowed at the beginning." });
    }
    
    // Check for multiple spaces (find first position)
    const multipleSpacesMatch = raw.match(/\s{2,}/);
    if (multipleSpacesMatch) {
        errors.push({ position: raw.indexOf(multipleSpacesMatch[0]), message: "Double spaces are not allowed." });
    }
    
    // Check for special characters (find first position) - allow hyphens
    for (let i = 0; i < raw.length; i++) {
        if (/[^a-zA-Z0-9\s-]/.test(raw[i])) {
            if (/_/.test(raw[i])) {
                errors.push({ position: i, message: "Only letters, spaces, and hyphens are allowed." });
        } else {
                errors.push({ position: i, message: "Special character is not allowed" });
        }
            break;
        }
    }
    
    // Check for digits (find first position)
    for (let i = 0; i < raw.length; i++) {
        if (/\d/.test(raw[i])) {
            errors.push({ position: i, message: "Numbers are not allowed." });
            break;
        }
    }
    
    // Check for space after hyphen
    const spaceAfterHyphen = /-\s/.exec(value);
    if (spaceAfterHyphen) {
        errors.push({ position: value.indexOf(spaceAfterHyphen[0]), message: "Remove the space after the hyphen." });
    }
    
    // Check for trailing space or hyphen
    if (raw.endsWith(' ') && raw.trim().length > 0) {
        errors.push({ position: raw.length - 1, message: "Cannot end with a space." });
    }
    if (value.endsWith('-')) {
        errors.push({ position: value.length - 1, message: "Barangay cannot end with a hyphen." });
    }
    
    // Check for consecutive letters
    const consecutiveMatch = value.match(/(.)\1{2,}/i);
    if (consecutiveMatch) {
        errors.push({ position: value.indexOf(consecutiveMatch[0]), message: "Three (3) consecutive letters are not allowed." });
    }
    
    // Check for all caps
    if (value === value.toUpperCase() && value.length > 1) {
        errors.push({ position: 0, message: "All capital letters are not allowed." });
    }
    
    // Check for consecutive capitals
    const consecutiveCapMatch = value.match(/([A-Z][A-Z])/);
    if (consecutiveCapMatch) {
        errors.push({ position: value.indexOf(consecutiveCapMatch[0]), message: "Consecutive capital letters are not allowed." });
    }
    
    // Check for max length
    if (value.length >= max) {
        errors.push({ position: max, message: `Maximum ${max} characters reached.` });
    }
    
    // Check capitalization errors
    if (value.length > 0) {
        if (!/^[A-Z]/.test(value)) {
            errors.push({ position: 0, message: "Barangay must start with a capital letter." });
        } else {
    const parts = value.split(/\s+/).filter(Boolean);
    if (parts.length >= 2 && /^[a-z]/.test(parts[1])) {
                const secondWordStart = value.indexOf(parts[1]);
                errors.push({ position: secondWordStart, message: "The second word must start with a capital letter." });
            }
        }
    }
    
    if (errors.length > 0) {
        errors.sort((a, b) => a.position - b.position);
        return errors[0].message;
    }
    
    return null;
}

// ✅ Helper function for City/Province/Country validation - no hyphens, no numbers
function findFirstErrorNoHyphen(raw, value, max) {
    const errors = [];
    
    // Check for leading space (position 0)
    if (raw.length > 0 && raw[0] === ' ') {
        errors.push({ position: 0, message: "Spaces are not allowed at the beginning." });
    }
    
    // Check for hyphen (find first position)
    const hyphenIndex = raw.indexOf('-');
    if (hyphenIndex !== -1) {
        errors.push({ position: hyphenIndex, message: "Hyphens are not allowed in this field." });
    }
    
    // Check for multiple spaces (find first position)
    const multipleSpacesMatch = raw.match(/\s{2,}/);
    if (multipleSpacesMatch) {
        errors.push({ position: raw.indexOf(multipleSpacesMatch[0]), message: "Double spaces are not allowed." });
    }
    
    // Check for special characters (find first position)
    for (let i = 0; i < raw.length; i++) {
        if (/[^a-zA-Z0-9\s]/.test(raw[i])) {
            errors.push({ position: i, message: "Special character is not allowed" });
            break;
        }
    }
    
    // Check for digits (find first position)
    for (let i = 0; i < raw.length; i++) {
        if (/\d/.test(raw[i])) {
            errors.push({ position: i, message: "Numbers are not allowed." });
            break;
        }
    }
    
    // Check for trailing space
    if (raw.endsWith(' ') && raw.trim().length > 0) {
        errors.push({ position: raw.length - 1, message: "Cannot end with a space." });
    }
    
    // Check for consecutive letters
    const consecutiveMatch = value.match(/(.)\1{2,}/i);
    if (consecutiveMatch) {
        errors.push({ position: value.indexOf(consecutiveMatch[0]), message: "Three (3) consecutive letters are not allowed." });
    }
    
    // Check for all caps
    if (value === value.toUpperCase() && value.length > 1) {
        errors.push({ position: 0, message: "All capital letters are not allowed." });
    }
    
    // Check for consecutive capitals
    const consecutiveCapMatch = value.match(/([A-Z][A-Z])/);
    if (consecutiveCapMatch) {
        errors.push({ position: value.indexOf(consecutiveCapMatch[0]), message: "Consecutive capital letters are not allowed." });
    }
    
    // Check for max length
    if (value.length >= max) {
        errors.push({ position: max, message: `Maximum ${max} characters reached.` });
    }
    
    // Check capitalization errors
    if (value.length > 0) {
        if (!/^[A-Z]/.test(value)) {
            errors.push({ position: 0, message: "Must start with a capital letter." });
        } else {
    const parts = value.split(/\s+/).filter(Boolean);
    if (parts.length >= 2 && /^[a-z]/.test(parts[1])) {
                const secondWordStart = value.indexOf(parts[1]);
                errors.push({ position: secondWordStart, message: "The second word must start with a capital letter." });
            }
        }
    }
    
    if (errors.length > 0) {
        errors.sort((a, b) => a.position - b.position);
        return errors[0].message;
        }
    
    return null;
    }
    
// ⚡ pwede nimo i-apply ang same structure sa Street, Barangay, City, Province, Country, Username, ug Suffix


// ✅ Real-time validation - Shows FIRST error from left to right
function validateStreet(){
    const input = document.getElementById("Street");
    const error = document.getElementById("streetError");
    const raw = input.value;
    const value = raw.trim();
    const max = parseInt(input.getAttribute("maxlength")) || 999;
    
    // ✅ Check if empty first
    if(value === ""){
        error.textContent = "Street is required.";
        input.classList.add("input-error");
        input.classList.remove("input-success");
        return;
    }

    // ✅ Check for hyphen at end FIRST (highest priority)
    if (value.endsWith('-')) {
        error.textContent = "Street cannot end with a hyphen.";
        input.classList.add("input-error");
        input.classList.remove("input-success");
        return;
    }
    
    // ✅ Find the first error from left to right
    const firstError = findFirstErrorStreet(raw, value, max);
    
    if (firstError) {
        error.textContent = firstError;
        input.classList.add("input-error");
        input.classList.remove("input-success");
        
        // Handle max length by truncating
        if (firstError.includes("Maximum")) {
            input.value = value.substring(0, max);
        }
        return;
    }
    
    // ✅ Check for lowercase letters after numbers (e.g., "P-3a" should be invalid)
    for (let i = 0; i < value.length - 1; i++) {
        if (/\d/.test(value[i]) && /[a-z]/.test(value[i + 1])) {
        input.classList.add("input-error");
        input.classList.remove("input-success");
            error.textContent = "After a number, letters must be uppercase.";
            return;
        }
    }
    
    // ✅ Final pattern check - allow numeric starts and uppercase letters after numbers (e.g., "12 Street", "P-3A")
    if (!/^([A-Z0-9][a-z0-9]*)([\s-][A-Z0-9][a-zA-Z0-9]*)*$/.test(value)) {
        input.classList.add("input-error");
        input.classList.remove("input-success");
        const incorrectChars = checkCapitalization(value);
        if (incorrectChars.length > 0) {
            error.textContent = incorrectChars.join(", ");
        } else {
            error.textContent = "Each word should start with a capital letter or number.";
        }
        return;
    }
    
    // ✅ SUCCESS: No errors found
    input.classList.remove("input-error");
    input.classList.add("input-success");
    error.textContent = "";
}
// ✅ Real-time validation - Shows FIRST error from left to right
function validateBarangay(){
    const input = document.getElementById("Barangay");
    const error = document.getElementById("barangayError");
    const raw = input.value;
    const value = raw.trim();
    const max = parseInt(input.getAttribute("maxlength")) || 999;
    
    // ✅ Check if empty first
    if(value === ""){
        error.textContent = "Barangay is required.";
        input.classList.add("input-error");
        input.classList.remove("input-success");
        return;
    }

    // ✅ Find the first error from left to right
    const firstError = findFirstErrorBarangay(raw, value, max);
    
    if (firstError) {
        error.textContent = firstError;
        input.classList.add("input-error");
        input.classList.remove("input-success");
        
        // Handle max length by truncating
        if (firstError.includes("Maximum")) {
            input.value = value.substring(0, max);
        }
        return;
    }
    
    // ✅ Final pattern check
    // ✅ UPDATED: Allow lowercase after hyphen (Caloc-an, La Union OK)
    if (!/^([A-Z][a-z]*)([\s-][A-Za-z0-9][a-z0-9]*)*$/.test(value)) {
        input.classList.add("input-error");
        input.classList.remove("input-success");
        const incorrectChars = checkCapitalization(value);
        if (incorrectChars.length > 0) {
            error.textContent = incorrectChars.join(", ");
        } else {
            error.textContent = "Each word should start with a capital letter.";
        }
        return;
    }
    
    // ✅ SUCCESS: No errors found
    input.classList.remove("input-error");
    input.classList.add("input-success");
    error.textContent = "";
}

// ✅ Real-time validation - Shows FIRST error from left to right
function validateCity(){
    const input = document.getElementById("City");
    const error = document.getElementById("cityError");
    const raw = input.value;
    const value = raw.trim();
    const max = parseInt(input.getAttribute("maxlength")) || 999;
    
    // ✅ Check if empty first
    if(value === ""){
        error.textContent = "City is required.";
        input.classList.add("input-error");
        input.classList.remove("input-success");
        return;
    }

    // ✅ Find the first error from left to right
    const firstError = findFirstErrorNoHyphen(raw, value, max);
    
    if (firstError) {
        error.textContent = firstError;
        input.classList.add("input-error");
        input.classList.remove("input-success");
        
        // Handle max length by truncating
        if (firstError.includes("Maximum")) {
            input.value = value.substring(0, max);
        }
        return;
    }
    
    // ✅ Final pattern check
    if (!/^([A-Z][a-z]*)(\s[A-Z][a-z0-9]*)*$/.test(value)) {
        input.classList.add("input-error");
        input.classList.remove("input-success");
        const incorrectChars = checkCapitalization(value);
        if (incorrectChars.length > 0) {
            error.textContent = incorrectChars.join(", ");
        } else {
            error.textContent = "Each word should start with a capital letter only.";
        }
        return;
    }
    
    // ✅ SUCCESS: No errors found
    input.classList.remove("input-error");
    input.classList.add("input-success");
    error.textContent = "";
}

// ✅ Real-time validation - Shows FIRST error from left to right
function validateProvince(){
    const input = document.getElementById("Province");
    const error = document.getElementById("provinceError");
    const raw = input.value;
    const value = raw.trim();
    const max = parseInt(input.getAttribute("maxlength")) || 999;
    
    // ✅ Check if empty first
    if(value === ""){
        error.textContent = "Province is required.";
        input.classList.add("input-error");
        input.classList.remove("input-success");
        return;
    }
    
    // ✅ Find the first error from left to right
    const firstError = findFirstErrorNoHyphen(raw, value, max);
    
    if (firstError) {
        error.textContent = firstError;
        input.classList.add("input-error");
        input.classList.remove("input-success");
        
        // Handle max length by truncating
        if (firstError.includes("Maximum")) {
            input.value = value.substring(0, max);
        }
        return;
    }
    
    // ✅ Final pattern check
    if (!/^([A-Z][a-z]*)(\s[A-Z][a-z0-9]*)*$/.test(value)) {
        input.classList.add("input-error");
        input.classList.remove("input-success");
        
        // Detailed capitalization error detection
        const incorrectChars = [];
        let wordStart = true;
        
        for (let i = 0; i < value.length; i++) {
            const char = value[i];
            
            if (char === ' ' || char === '-') {
                wordStart = true;
            } else if (/[a-zA-Z]/.test(char)) {
                if (wordStart) {
                    // First letter of word should be uppercase
                    if (char === char.toLowerCase()) {
                        incorrectChars.push(`'${char}' should be uppercase`);
                    }
                    wordStart = false;
                } else {
                    // Non-first letters should be lowercase
                    if (char === char.toUpperCase()) {
                        incorrectChars.push(`'${char}' should be lowercase`);
                    }
                }
            }
        }
        
        error.textContent = incorrectChars.join(", ");
        return;
    }
    
    // ✅ SUCCESS: No errors found
    input.classList.remove("input-error");
    input.classList.add("input-success");
    error.textContent = "";
}

// ✅ Real-time validation - Shows FIRST error from left to right
function validateCountry(){
    const input = document.getElementById("Country");
    const error = document.getElementById("countryError");
    const raw = input.value;
    const value = raw.trim();
    const max = parseInt(input.getAttribute("maxlength")) || 999;
    
    // ✅ Check if empty first
    if(value === ""){
        error.textContent = "Country is required.";
        input.classList.add("input-error");
        input.classList.remove("input-success");
        return;
    }
    
    // ✅ Find the first error from left to right
    const firstError = findFirstErrorNoHyphen(raw, value, max);
    
    if (firstError) {
        error.textContent = firstError;
        input.classList.add("input-error");
        input.classList.remove("input-success");
        
        // Handle max length by truncating
        if (firstError.includes("Maximum")) {
        input.value = value.substring(0, max);
        }
        return;
    }
    
    // ✅ Final pattern check
    if (!/^([A-Z][a-z]*)([\s-][A-Z][a-z0-9]*)*$/.test(value)) {
        input.classList.add("input-error");
        input.classList.remove("input-success");
        
        // Detailed capitalization error detection
        const incorrectChars = [];
        let wordStart = true;
        
        for (let i = 0; i < value.length; i++) {
            const char = value[i];
            
            if (char === ' ' || char === '-') {
                wordStart = true;
            } else if (/[a-zA-Z]/.test(char)) {
                if (wordStart) {
                    // First letter of word should be uppercase
                    if (char === char.toLowerCase()) {
                        incorrectChars.push(`'${char}' should be uppercase`);
                    }
                    wordStart = false;
                } else {
                    // Non-first letters should be lowercase
                    if (char === char.toUpperCase()) {
                        incorrectChars.push(`'${char}' should be lowercase`);
                    }
                }
            }
        }
        
        error.textContent = incorrectChars.join(", ");
        return;
    }
    
    // ✅ SUCCESS: No errors found
    input.classList.remove("input-error");
    input.classList.add("input-success");
    error.textContent = "";
}

// ✅ Birthday required validation
function validateBirthday(){
    const input = document.getElementById("birthday");
    if (!input) return;
    const error = ensureErrorElement('birthdayError', input);
    if (!error) return;
    const value = input.value;
    if (!value){
        error.textContent = "Birthday is required.";
        input.classList.add("input-error");
        input.classList.remove("input-success");
    } else {
        // Check if the year is beyond 2025
        const birthdate = new Date(value);
        const birthYear = birthdate.getFullYear();
        const currentYear = new Date().getFullYear();
        
        if (birthYear > 2025) {
            error.textContent = "Age Must not be in a future";
            input.classList.add("input-error");
            input.classList.remove("input-success");
        } else if (birthdate > new Date()) {
            // Also check if the date itself is in the future
            error.textContent = "Age Must not be in a future";
            input.classList.add("input-error");
            input.classList.remove("input-success");
        } else {
            error.textContent = "";
            input.classList.remove("input-error");
            input.classList.add("input-success");
        }
    }
}

// ✅ Ensure error container exists for a field
function ensureErrorElement(id, afterElement) {
    let el = document.getElementById(id);
    if (!el && afterElement && afterElement.parentNode) {
        el = document.createElement('div');
        el.id = id;
        el.className = 'error-message';
        afterElement.parentNode.appendChild(el);
    }
    return el;
}

// ✅ Sex (gender) required validation
function validateGender(){
    const select = document.getElementById('gender');
    if (!select) return;
    const error = ensureErrorElement('genderError', select);
    if (!error) return;
    const value = select.value;
    if (!value || value.trim() === ''){
        error.textContent = 'Sex is required.';
        select.classList.add('input-error');
        select.classList.remove('input-success');
    } else {
        error.textContent = '';
        select.classList.remove('input-error');
        select.classList.add('input-success');
    }
}

// ✅ Zip Code simple required validation
function validateZipCode(){
    const input = document.getElementById("ZipCode");
    if (!input) return;
    const error = ensureErrorElement('zipCodeError', input);
    if (!error) return;
    
    // Keep only digits and enforce max length 4
    input.value = input.value.replace(/\D/g, '').slice(0, 4);
    const value = input.value.trim();
    
    // ✅ Show error even if empty (required field)
    if (value === ""){
        error.textContent = "Zip Code is required.";
        input.classList.add("input-error");
        input.classList.remove("input-success");
    } else if (!/^\d{4}$/.test(value)) {
        error.textContent = "Zip Code must be 4 digits.";
        input.classList.add("input-error");
        input.classList.remove("input-success");
    } else {
        error.textContent = "";
        input.classList.remove("input-error");
        input.classList.add("input-success");
    }
}
function validateSuffix() {
    const input = document.getElementById("suffix");
    const error = document.getElementById("suffixError");
    const raw = input.value;
    const value = raw.trim();
    const multipleSpacesPattern = /\s{2,}/; // Check for multiple consecutive spaces

    // Roman numerals that are allowed
    const allowedRomanNumerals = ["I", "II", "III", "IV", "V", "VI", "VII", "VIII", "IX", "X", "XI", "XII", "XIII", "XIV", "XV"];
    const upperValue = value.toUpperCase();
    const isRomanNumeral = allowedRomanNumerals.includes(upperValue);

    // Valid suffixes: only "Jr" and "Sr" are allowed (case-sensitive)
    const allowedSuffixes = ["Jr", "Sr"];

    // Check if input ends with a space
    if (raw.endsWith(' ') && raw.trim().length > 0) {
        error.textContent = "Cannot end with a space.";
        input.classList.add("input-error");
        input.classList.remove("input-success");
        return;
    }

    if (multipleSpacesPattern.test(raw)) {
        error.textContent = "Double spaces are not allowed.";
        input.classList.add("input-error");
        input.classList.remove("input-success");
        return;
    }

    if (value === "") {
        // Optional field - no error when empty
        input.classList.remove("input-error");
        input.classList.remove("input-success");
        error.textContent = "";
        return;
    }

    // Check if it's a valid suffix (Jr or Sr)
    if (allowedSuffixes.includes(value)) {
        input.classList.remove("input-error");
        input.classList.add("input-success");
        error.textContent = "";
        return;
    }

    // Check if it's a valid Roman numeral
    if (isRomanNumeral) {
        input.classList.remove("input-error");
        input.classList.add("input-success");
        error.textContent = "";
        return;
    }

    // Reject "Rj" and any other invalid input
    input.classList.add("input-error");
    input.classList.remove("input-success");
    error.textContent = "Invalid format. Only 'Jr', 'Sr', or Roman numerals (I-XV) are allowed.";
}

// ✅ Password length and strength validation
function validatePassword(){
    const input = document.getElementById("Password");
    if (!input) return;
    
    const error = document.getElementById("passwordError");
    const strength = document.getElementById("passwordStrength");
    const value = input.value;
    const min = 8;
    const max = 20;

    // ✅ Priority 1: Check for leading space FIRST - show error immediately
    if (value.length > 0 && value[0] === ' ') {
        if (error) {
            error.textContent = "Spaces are not allowed in the password.";
            error.style.color = "red";
        }
        input.classList.add("input-error");
        input.classList.remove("input-success");
        input.style.borderColor = "red";
        // Clear strength indicator
        if (strength) {
            strength.textContent = "";
            strength.style.color = "";
            strength.style.display = "";
        }
        return; // Stop here - don't proceed with other validations
    }

    // ✅ Priority 2: If empty, show error immediately and clear strength - NO EXCEPTIONS
    if (value.length === 0 || value.trim() === ""){
        if (error) {
        error.textContent = "Password is required.";
            error.style.color = "red";
        }
        input.classList.add("input-error");
        input.classList.remove("input-success");
        input.style.borderColor = "red";
        // Force clear strength indicator immediately
        if (strength) {
        strength.textContent = "";
            strength.style.color = "";
            strength.style.display = "";
        }
        return; // Stop here - don't do anything else
    } else if (value.length < min){
        error.textContent = `Minimum ${min} characters required.`;
        input.classList.add("input-error");
        input.classList.remove("input-success");
        strength.textContent = "";
    } else if (value.length >= max){
        input.value = value.substring(0, max);
        error.textContent = `Maximum ${max} characters reached.`;
        input.classList.add("input-error");
        input.classList.remove("input-success");
        strength.textContent = "";
    } else {
        // Only show strength indicator if password meets minimum length
        if (value.length >= min) {
        error.textContent = "";
        input.classList.remove("input-error");
        input.classList.add("input-success");
        // Don't set strength indicator here - let check_user.js handle it to avoid duplicates
        // check_user.js will show "Weak", "Medium", or "Strong" properly
        if (strength) {
            // Clear any previous strength indicator from register.js
            // check_user.js will set the proper one
        }
        } else {
            // If somehow we get here with length < min, show error
            error.textContent = `Minimum ${min} characters required.`;
            input.classList.add("input-error");
            input.classList.remove("input-success");
            strength.textContent = "";
        }
    }
    // ✅ Removed automatic confirm password validation - only validate when user types in confirm password field
}

function validateConfirmPassword(){
    const pwd = document.getElementById("Password").value;
    const confirmInput = document.getElementById("RePassword");
    if (!confirmInput) return;
    
    const confirm = confirmInput.value;
    const error = document.getElementById("confirmPasswordError");
    
    // ✅ Only show "required" error if field was touched (has been focused or has value before)
    // Check if field has been interacted with by checking if it has the 'touched' class or has had a value
    const wasTouched = confirmInput.classList.contains('touched') || confirmInput.dataset.wasTouched === 'true';
    
    // ✅ Show error when confirm password is empty ONLY if field was touched
    if ((confirm.length === 0 || confirm.trim() === "") && wasTouched){
        if (error) {
            error.textContent = "Confirm password is required.";
            error.style.color = "red";
        }
        confirmInput.classList.add("input-error");
        confirmInput.classList.remove("input-success");
        confirmInput.style.borderColor = "red";
        return;
    }
    
    // ✅ If empty and not touched, clear any errors and return
    if (confirm.length === 0 || confirm.trim() === ""){
        if (error) {
            error.textContent = "";
        }
        confirmInput.classList.remove("input-error");
        confirmInput.classList.remove("input-success");
        confirmInput.style.borderColor = "";
        return;
    }
    if (pwd !== confirm){
        if (error) {
        error.textContent = "Passwords do not match.";
            error.style.color = "red";
        }
        confirmInput.classList.add("input-error");
        confirmInput.classList.remove("input-success");
        confirmInput.style.borderColor = "red";
    } else {
        if (error) {
        error.textContent = "";
        }
        confirmInput.classList.remove("input-error");
        confirmInput.classList.add("input-success");
        confirmInput.style.borderColor = "green";
    }
}

// ✅ Helper function for detailed capitalization validation
function checkCapitalization(value) {
    const incorrectChars = [];
    let wordStart = true;
    
    for (let i = 0; i < value.length; i++) {
        const char = value[i];
        
        if (char === ' ' || char === '-') {
            wordStart = true;
        } else if (/[a-zA-Z]/.test(char)) {
            if (wordStart) {
                // First letter of word should be uppercase
                if (char === char.toLowerCase()) {
                    incorrectChars.push(`'${char}' should be uppercase`);
                }
                wordStart = false;
            } else {
                // Non-first letters should be lowercase
                if (char === char.toUpperCase()) {
                    incorrectChars.push(`'${char}' should be lowercase`);
                }
            }
        }
    }
    
    return incorrectChars;
}

// ✅ Toggle Middle Name and Suffix optional checkboxes
document.addEventListener('DOMContentLoaded', function () {
    const middleInput = document.getElementById('middleName');
    const middleError = document.getElementById('middleNameError');
    const noMiddleCheckbox = document.getElementById('noMiddleName');

    const suffixInput = document.getElementById('suffix');
    const suffixError = document.getElementById('suffixError');
    const noSuffixCheckbox = document.getElementById('noSuffix');
    const toggleRegPassword = document.getElementById('toggleRegPassword');
    const toggleRegRePassword = document.getElementById('toggleRegRePassword');
    const usernameField = document.getElementById('Username');
    const form = document.getElementById('registerForm');
    const birthdayField = document.getElementById('birthday');
    const genderField = document.getElementById('gender');
    const zipCodeField = document.getElementById('ZipCode');
    const firstNameField = document.getElementById('fname');
    const lastNameField = document.getElementById('LastName');

    // Auto-format helper: title-case per word while typing (uppercase only at word starts)
    function autoTitleCase(el){
        if (!el) return;
        el.addEventListener('input', function(){
            const original = this.value;
            // Collapse multiple spaces but keep single space while typing
            const collapsed = original.replace(/\s{2,}/g, ' ');
            const parts = collapsed.split(' ');
            for (let i = 0; i < parts.length; i++){
                const p = parts[i];
                if (p.length === 0) continue;
                parts[i] = p.charAt(0).toUpperCase() + p.slice(1).toLowerCase();
            }
            const formatted = parts.join(' ');
            if (formatted !== this.value){
                this.value = formatted;
            }
        });
    }

    if (noMiddleCheckbox && middleInput) {
        noMiddleCheckbox.addEventListener('change', function () {
            if (this.checked) {
                middleInput.value = '';
                middleInput.disabled = true;
                middleInput.classList.remove('input-error', 'input-success');
                if (middleError) middleError.textContent = '';
            } else {
                middleInput.disabled = false;
            }
        });
    }

    if (noSuffixCheckbox && suffixInput) {
        noSuffixCheckbox.addEventListener('change', function () {
            if (this.checked) {
                suffixInput.value = '';
                suffixInput.disabled = true;
                suffixInput.classList.remove('input-error', 'input-success');
                if (suffixError) suffixError.textContent = '';
            } else {
                suffixInput.disabled = false;
            }
        });
    }

    // Toggle password visibility with eye icon
    if (toggleRegPassword) {
        toggleRegPassword.addEventListener('click', function(){
            const pwd = document.getElementById('Password');
            if (pwd.type === 'password') {
                pwd.type = 'text';
                toggleRegPassword.classList.remove('fa-eye');
                toggleRegPassword.classList.add('fa-eye-slash');
            } else {
                pwd.type = 'password';
                toggleRegPassword.classList.remove('fa-eye-slash');
                toggleRegPassword.classList.add('fa-eye');
            }
        });
    }
    if (toggleRegRePassword) {
        toggleRegRePassword.addEventListener('click', function(){
            const repwd = document.getElementById('RePassword');
            if (repwd.type === 'password') {
                repwd.type = 'text';
                toggleRegRePassword.classList.remove('fa-eye');
                toggleRegRePassword.classList.add('fa-eye-slash');
            } else {
                repwd.type = 'password';
                toggleRegRePassword.classList.remove('fa-eye-slash');
                toggleRegRePassword.classList.add('fa-eye');
            }
        });
    }

    // Wire up live validation for Username
    if (usernameField && typeof validateUsernameStrict === 'function'){
        usernameField.addEventListener('input', validateUsernameStrict);
        usernameField.addEventListener('blur', validateUsernameStrict);
    }
    // ✅ Password validation - ensure error shows when field is cleared
    const passwordField = document.getElementById('Password');
    if (passwordField && typeof validatePassword === 'function'){
        passwordField.addEventListener('blur', validatePassword);
    }
    // ✅ Confirm password validation - ensure error shows when field is cleared
    const confirmPasswordField = document.getElementById('RePassword');
    if (confirmPasswordField && typeof validateConfirmPassword === 'function'){
        // Mark field as touched when user focuses on it
        confirmPasswordField.addEventListener('focus', function() {
            this.classList.add('touched');
            this.dataset.wasTouched = 'true';
        });
        confirmPasswordField.addEventListener('input', function() {
            this.classList.add('touched');
            this.dataset.wasTouched = 'true';
            validateConfirmPassword();
        });
        confirmPasswordField.addEventListener('blur', validateConfirmPassword);
    }
    // Keep user input as-is (no auto title-casing) so we can show errors for all-caps
    if (birthdayField && typeof validateBirthday === 'function'){
        birthdayField.addEventListener('change', validateBirthday);
        birthdayField.addEventListener('blur', validateBirthday);
    }
    if (genderField && typeof validateGender === 'function'){
        genderField.addEventListener('change', validateGender);
        genderField.addEventListener('blur', validateGender);
    }
    if (zipCodeField && typeof validateZipCode === 'function'){
        // Ensure no spinners and numeric-only UX
        try { zipCodeField.type = 'text'; } catch (_) {}
        zipCodeField.setAttribute('inputmode', 'numeric');
        zipCodeField.setAttribute('maxlength', '4');
        zipCodeField.setAttribute('pattern', '\\d{4}');
        // Hard limit to 4 digits on input
        zipCodeField.addEventListener('input', function(){
            this.value = this.value.replace(/\D/g, '').slice(0, 4);
        });
        zipCodeField.addEventListener('input', validateZipCode);
        zipCodeField.addEventListener('blur', validateZipCode);
    }

    // ✅ Attach leading space prevention to all text input fields
    const textInputFields = [
        { input: document.getElementById('fname'), error: document.getElementById('fnameError') },
        { input: document.getElementById('middleName'), error: document.getElementById('middleNameError') },
        { input: document.getElementById('LastName'), error: document.getElementById('lastNameError') },
        { input: document.getElementById('suffix'), error: document.getElementById('suffixError') },
        { input: document.getElementById('Street'), error: document.getElementById('streetError') },
        { input: document.getElementById('Barangay'), error: document.getElementById('barangayError') },
        { input: document.getElementById('City'), error: document.getElementById('cityError') },
        { input: document.getElementById('Province'), error: document.getElementById('provinceError') },
        { input: document.getElementById('Country'), error: document.getElementById('countryError') }
    ];

    textInputFields.forEach(function(field) {
        if (field.input && field.error) {
            preventLeadingSpaceOnInput(field.input, field.error);
        }
    });

    // Disable native HTML5 tooltip and route submit through our custom validator
    if (form) {
        form.noValidate = true;
        form.addEventListener('submit', function (e) {
            // Also validate gender before submit
            if (typeof validateGender === 'function') validateGender();
            if (!validateForm()) {
                e.preventDefault();
            } else if (!confirm('Continue to security questions?')) {
                e.preventDefault();
            }
        });
    }
});

